import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm") version "2.1.20"
    kotlin("plugin.serialization") version "2.1.20"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))

    // Use the Kotlin JDK 8 standard library.
    implementation(libs.org.jetbrains.kotlinx.coroutines.core)
    implementation(libs.bundles.io.ktor)
    implementation(libs.com.github.ajalt.clikt)
    implementation(libs.org.jetbrains.kotlinx.serialization.json)
    implementation(libs.icure.sdk)
    implementation(libs.xerces)
    implementation(libs.io.github.reidsync.kotlin.json.patch)
}

kotlin {
    jvmToolchain(21)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.jar {
    manifest {
        attributes(
            mapOf(
                "Implementation-Title" to rootProject.name,
                "Implementation-Version" to project.version,
                "Root-Commands" to "com.icure.cli.commands.api.Api",
            )
        )
    }
    archiveBaseName.set(rootProject.name)
    finalizedBy("copyJar")
}


tasks.register("copyJar", Copy::class) {
    dependsOn("jar")
    from(layout.buildDirectory.dir("libs"))
    into(layout.projectDirectory.dir("../icure-cli/plugins"))
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
